# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='people',
            new_name='count',
        ),
    ]
