# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170410_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
