# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 14:43
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170417_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.DateTimeField(default=api.models.local_time),
        ),
    ]
