# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170417_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
